- name: Configure aptitude to include stable, testing, unstable and experimental
  import_tasks: debian_apt_pref.yml
  when: do_aptpref == "yes"

- name: Install development packages
  ansible.builtin.apt:
    name:
      - build-essential
      - make
      - exuberant-ctags
      - git
      - python3-pip
      - pipx
      - python3-setuptools
      - python3-virtualenv
      - python3-pexpect
      - libaio-dev
      - pkgconf
      - libgflags-dev
      - liblz4-dev
      - cmake
      - libslirp-dev
      - libglib2.0-dev
      - socat
      - libpixman-1-dev
      - libssl-dev
      - libjson-c-dev
      - gdb
      - rsync
      - mosh
      - tmux
      - bison
      - flex
      - ncurses-dev
      - libelf-dev
      - bc
      - zsh
      - fzf
      - mc
      - curl
      - rake
      - systemd-timesyncd
      - neomutt
      - abook
      - mailcap
      - msmtp
      - iptables
      - btop
      - ccache
      - isync
      - meson
      # for the kernel
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
    state: present
    update_cache: no
  become: true
  become_method: sudo
  become_user: root

#- name: Install from URL
#  ansible.builtin.apt:
#    deb: "https://discord.com/api/download?platform=linux&format=deb"
#  become: true
#  become_method: sudo
#  become_user: root
#
#- name: Configure aptitude to include stable, testing, unstable and experimental
#  import_tasks: debian_apt_pref.yml
